import Head from 'next/head';
import React from 'react';
import quotes from '../data/quotes_unlimited.json';

const Quotes = () => {
  const quoteslen = quotes.length;
  return (
    <div className=''>
      <Head>
        <title>QuotesAddicter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/quote.png" />
      </Head>

      <main>
        <div>
          <h1 className='text-center text-3xl font-semibold'>Unlimited Quotes</h1>
        </div>
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-wrap -mx-4 -my-8">
              {
                quotes.map((quote) => {
                  return <div className="py-8 px-4 lg:w-1/3">
                    <div className="h-full flex items-start bg-gray-50 bg-opacity-75 px-8 pt-16 pb-16 rounded-xl  shadow-xl shadow-blue-300 hover:bg-blue-100 hover:shadow-orange-300">
                      <div className="flex-grow pl-6">
                        <h1 className="title-font text-xl font-medium text-gray-900 mb-3">"{quote.text}"</h1>
                        {quote.author && <div className="inline-flex items-center">
                          <div className="inline-flex overflow-hidden relative justify-center items-center w-10 h-10 bg-gray-100 rounded-full dark:bg-gray-600 ">
                            <span className="font-medium text-gray-600 dark:text-gray-300">{quote.author.split(' ').map(word => word[0])}</span>
                          </div>
                          <div className="flex-grow flex flex-col pl-3">
                            <span className="title-font font-medium text-gray-900">-{quote.author}</span>
                          </div>
                        </div>
                        }
                      </div>
                    </div>

                  </div>


                })
              } </div>

          </div>
        </section>
      </main>


    </div>
  )
}

export default Quotes