import Head from 'next/head';
import React, { useState } from 'react';
import quotes from '../data/quotes_unlimited.json';

const Random = () => {
    // var randomNum = Math.floor(Math.random() * quotes.length);
    const [randomNumber, setrandomNumber] = useState(Math.floor(Math.random() * quotes.length));
    function genRandomNum() {
        setrandomNumber(Math.floor(Math.random() * quotes.length));
    }

    return (
        <div>
            <Head>
                <title>Quote of the Day</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/quote.png" />
            </Head>
            <main className="">
                <h1 className='text-center text-3xl font-semibold'>Quote Of The Day</h1>
                <div className="flex justify-center">
                    <div className="flex flex-col justify-center">
                        <div className="flex flex-col md:flex-row max-w-7xl justify-center items-center">
                            <div className="overflow-hidden w-full m-4 flex justify-center rounded-2xl">
                                <div
                                    className="flex flex-col md:flex-row items-center justify-center shadow-md h-full text-white bg-blue-500 hover:bg-orange-500 ">
                                    <div className=" w-1/2 overflow-hidden ">
                                        <div className="flex flex-col justify-center h-full p-5">
                                            <div className="font-semibold md:text-5xl text-3xl m-2">"{quotes[randomNumber].text}" </div>
                                            <div className=" m-2 text-xl"><a href="#">{quotes[randomNumber].author}</a></div>
                                        </div>
                                    </div>
                                    <div className=" md:w-1/2 overflow-hidden "> <img src="https://source.unsplash.com/700x600/?inspiration"
                                        alt="" className="" /> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='flex justify-center'>
                    <button onClick={genRandomNum} className=' px-5 py-3 text-white bg-blue-500 hover:bg-orange-500  rounded-lg'>Get New Quote</button>
                </div>
            </main>
        </div>
    )
}

export default Random

// export async function getServerSideProps(context) {
//     return {
//         props: { quotes }, // will be passed to the page component as props
//     }
// }
